name: 'Publish component'
description: 'Publish component and documentation'

inputs:
  ssh-key:
    required: True
  publish-directory:
    required: True
    default: /tmp/publish
  release-directory:
    required: True
    default: /tmp/release
  gh-token:
    required: True

runs:
  using: "composite"
  steps:
    - run: |
        mkdir -p ${{inputs.publish-directory}}
        mkdir -p ${{inputs.release-directory}}
      shell: bash

    - name: Setup SSH
      shell: bash
      run: |
        cd $HOME
        pwd
        mkdir .ssh
        echo "$SSH_KEY" > .ssh/id_rsa
        chmod 600 .ssh/id_rsa
      env:
        SSH_KEY: ${{inputs.ssh-key}}

    - name: Checkout style
      uses: actions/checkout@v2
      with:
        repository: aardsoft/style
        path: style
        token: "${{ inputs.gh-token }}"

    - name: Build page
      uses: aardsoft/publish-org-tree@master
      with:
        publish-directory: "${{inputs.publish-directory}}"
      env:
        org_publish_function: org-html-publish-to-templated-html
        project_directory: doc
        default_page_template: page_with_inline_sidebar.html
        template_directory: ../style/templates
        style_directory: ../style
        GH_TOKEN: ${{inputs.gh-token}}

    - name: Build archives
      run: ${{ github.action_path}}/pack.sh
      shell: bash
      env:
        release_dir: "${{inputs.release-directory}}"
        publish_dir: "${{inputs.publish-directory}}"